#!/bin/bash

export SOMP_OVERLAP=1
export SOMP_SCHEDCACHE=0
export SOMP_SCRATCHW=0
export SOMP_CACHELOCK=1
export SOMP_SERIALRW=1
export SOMP_OVERLAPR=1
export SOMP_OVERLAPRATIO=0,6
export SOMP_TRACETIME=1
